### ISSUE TITLE
Update webpack and webpack-dev-server version

### ISSUE THREAD

**Issue by NemoAlex** [schovi/webpack-chrome-extension#27]
Problem: //@ sourceURL and //@ sourceMapURL is deprecated
Solution: upgrade webpack and webpack-dev-server to latest version.

**Comment by schovi** [comment]
@NemoAlex There is problem. Functionality of this environment dependent on webpack "hack".

Hack is nothing more, then dummy override 2 files inside `node_modules/webpack`

1) Reloading chrome extension when hot module is not available
https://github.com/schovi/webpack-chrome-extension/blob/master/dev-env/override/template/JsonpMainTemplate.runtime.js

2) MOST IMPORTANT PART: run hot module updates in correct context of chrome extension and not page itself.
https://github.com/schovi/webpack-chrome-extension/blob/master/dev-env/override/template/log-apply-results.js

It is few months since I tried to update webpack, but it failed, because I cant make it works again like that. I rename this issue to more related name and feel free to dig into that :)

**Comment by schovi** [comment]
Simply temporary soution.
Filter console by regexp `^((?!sourceURL).)*$` :)

**Comment by schovi** [comment]
Solved with https://github.com/schovi/webpack-chrome-extension/commit/51a1b248afbea4d91638257e6c27ef8782107262
